#### Pandas For Data Analysis
1) Pandas is a python package providing fast,flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive.
 2) It was created by Wes McKinney in 2008

 Applications : 
 1) Easy Handling
 2) Size Mutability : Columns can be inserted and deleted from DataFrame and higher dimensional obejcts
 3) Automatic align the data for you in computations
 4) Powerful,flexible group by functionality.
 5) Flexible reshaping and pivoting of data sets.

 Pandas Series is a one-dimesnional labeled array capable of holding data of any type(integer,string,float,python objects,etc)

 The axis labels are collectively called index. Pandas Series is nothing but a column in an excel sheet.

 The objects supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.

##### Creation of DataFrames in Pandas

In [14]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\bhaga\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\bhaga\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)

##### Exploring Data in Pandas

##### read_csv() or read_excel() : This function to read data stored as a csv or excel file into a pandas.

In [15]:
import pandas as pd

df = pd.read_excel("ESD.xlsx")
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

##### head() : It is used to see the first N rows of a DataFrame. N = 1,2,3,........no of rows u want to see

In [16]:
df.head(5)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

##### tail() :  It is used to see the Last N rows of a DataFrame. Where N = 1 ,2 ,3, 4,........no of rows u want to see

In [17]:
df.tail(10)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
990,E01578,Anthony Hong,Sr. Manger,IT,Research & Development,Male,Asian,37,2010-11-29,146961,0.11,United States,Columbus,NaT
991,E03430,Leo Herrera,Sr. Business Partner,Human Resources,Research & Development,Male,Latino,48,1998-04-22,85369,0.00,Brazil,Manaus,2004-11-27
992,E03058,Robert Wright,Technical Architect,IT,Manufacturing,Male,Caucasian,30,2015-06-14,67489,0.00,United States,Chicago,NaT
993,E04762,Audrey Richardson,Director,IT,Manufacturing,Female,Caucasian,46,2018-10-06,166259,0.17,United States,Chicago,NaT
994,E01148,Scarlett Kumar,Systems Analyst,IT,Corporate,Female,Asian,55,2009-01-07,47032,0.00,United States,Columbus,NaT
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

##### info() : The method info() provides technical information about a DataFrame.

In [18]:
df.info()  # It displays the data types,columns,etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      1000 non-null   object
 2   Job Title      1000 non-null   object
 3   Department     1000 non-null   object
 4   Business Unit  1000 non-null   object
 5   Gender         1000 non-null   object
 6   Ethnicity      1000 non-null   object
 7   Age            1000 non-null   int64
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64
 10  Bonus %        1000 non-null   float64
 11  Country        1000 non-null   object
 12  City           1000 non-null   object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 109.5+ KB

##### describe() : The describe() method provides a quick overview of the numerical data in a DataFrame.

In [19]:
df.describe()

,Age,Hire Date,Annual Salary,Bonus %,Exit Date
count,1000.000000,1000,1000.000000,1000.000000,85
mean,44.382000,2012-04-07 02:54:14.400000,113217.365000,0.088660,2016-11-02 18:04:14.117647104
min,25.000000,1992-01-09 00:00:00,40063.000000,0.000000,1994-12-18 00:00:00
25%,35.000000,2007-02-14 00:00:00,71430.250000,0.000000,2014-12-25 00:00:00
50%,45.000000,2014-02-15 12:00:00,96557.000000,0.000000,2019-05-23 00:00:00
75%,54.000000,2018-06-22 00:00:00,150782.250000,0.150000,2021-04-09 00:00:00
max,65.000000,2021-12-26 00:00:00,258498.000000,0.400000,2022-08-17 00:00:00
std,11.246981,NaN,53545.985644,0.117856,NaN

##### isnull().sum() : Used to identify the number of missing (null/NaN) values in each column of a DataFrame.

In [21]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
dtype: int64

##### Handling the Duplicate Values

In [24]:
df["Exit Date"].duplicated().sum()

np.int64(916)

In [25]:
df.drop_duplicates("Exit Date")

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20
14,E03496,Robert Yang,Sr. Analyst,Accounting,Speciality Products,Male,Asian,31,2017-11-04,97078,0.00,United States,Austin,2020-03-09
40,E01754,Owen Lam,Sr. Business Partner,Human Resources,Speciality Products,Male,Asian,30,2017-05-29,86317,0.00,China,Chengdu,2017-07-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,E03305,Cooper Jiang,Analyst II,Accounting,Corporate,Male,Asian,49,2019-07-25,50883,0.00,China,Chongqing,2021-03-02
982,E03247,Aaliyah Mai,Vice President,IT,Speciality Products,Female,Asian,57,2016-11-11,246589,0.33,United States,Phoenix,2017-03-26
983,E02703,Austin Vang,Manager,Marketing,Speciality Products,Male,Asian,49,2018-05-20,119397,0.09,China,Beijing,2019-03-14
991,E03430,Leo Herrera,Sr. Business Partner,Human Resources,Research & Development,Male,Latino,48,1998-04-22,85369,0.00,Brazil,Manaus,2004-11-27
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08

##### Working with Missing Data

In [33]:
import pandas as pd
import numpy as np 

df = pd.read_csv("company1.csv")
df

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [29]:
df.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [30]:
df.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [31]:
df

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [34]:
df.replace(np.nan,30000)

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali  30000  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     30000      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [46]:
df["salary"] = df["salary"].replace(np.nan,24400)
print(df)
print("Mean : ", df["salary"].mean())

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0
Mean :  26000.0

In [45]:
df["salary"].mean()

np.float64(26000.0)

In [47]:
df.fillna(method= "bfill")

C:\Users\bhaga\AppData\Local\Temp\ipykernel_19712\3528466224.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method= "bfill")

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [48]:
df.fillna(method="ffill")

C:\Users\bhaga\AppData\Local\Temp\ipykernel_19712\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      M  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05    ayushi      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

##### Columns Transformation

In [52]:
import pandas as pd

data = pd.read_excel("ESD.xlsx")
data.loc[(data["Bonus %"] == 0), "GetBonus"] = "no bonus"
data.loc[(data["Bonus %"] > 0, "GetBonus")] = "bonus"
data.head(10)

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,GetBonus
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,bonus
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT,no bonus
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT,bonus
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT,bonus
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT,no bonus
5,E00644,Joshua Gupta,Account Representative,Sales,Corporate,Male,Asian,57,2017-01-24,50994,0.00,China,Chongqing,NaT,no bonus
6,E01550,Ruby Barnes,Manager,IT,Corporate,Female,Caucasian,27,2020-07-01,119746,0.10,United States,Phoenix,NaT,bonus
7,E04332,Luke Martin,Analyst,Finance,Manufacturing,Male,Black,25,2020-05-16,41336,0.00,United States,Miami,2021-05-20,no bonus
8,E04533,Easton Bailey,Manager,Accounting,Manufacturing,Male,Caucasian,29,2019-01-25,113527,0.06,United States,Austin,NaT,bonus
9,E03838,Madeline Walker,Sr. Analyst,Finance,Speciality Products,Female,Caucasian,34,2018-06-13,77203,0.00,United States,Chicago,NaT,no bonus